### ISSUE TITLE
km marker colours due to order

### ISSUE THREAD

**Issue by kylemath** [korymath/runkeeper-testing#2]
so your automation of the km markers screwed up the colour coating
now it does all the KM markers, than all the mile markers, 
this means if there is a km2 it gets the same marker colour as the Mile 1 should have had (matlab colours items in order)

**Comment by kylemath** [comment]
![image](https://cloud.githubusercontent.com/assets/3662613/15515547/eb11cda8-21ab-11e6-94cd-f7334c2dab86.png)

**Comment by korymath** [comment]
This is the right place to make this comment.

**Comment by korymath** [comment]
Desired appearance would be color order is the same for km and mile?

So KM_i_color = Mile_i_color?

**Comment by korymath** [comment]
This is also potentially an issue when there are two runs plotted.... 

Then KM1_run1_color is not the same as KM1_run2_color... but I am not sure what is desirable?

**Comment by kylemath** [comment]
The goal is every first KM one colour, every first mile another colour, so you can visually see the progression by attending to colour.

Matlab assigns scatterplot colours in order if you don't specify, first one C1, then C2

before we stepped through the distances in order Km1, Mile1, Km2, Km3, Mile2, etc. so it just happened to put the colour the same for each of the same distance accross runs

Now you have it do all the KM, than all the Mile
so we could just specify a marker colour unique for each distance, and force it to use that marker colour

**Comment by korymath** [comment]
Or modify the loops, which may be the easiest way, and help us lose one of
the loops... incoming change.

On Tue, May 24, 2016 at 12:59 PM, Kyle Mathewson <notifications@github.com>
wrote:

> The goal is every first KM one colour, every first mile another colour, so
> you can visually see the progression by attending to colour.
>
> Matlab assigns scatterplot colours in order if you don't specify, first
> one C1, then C2
>
> before we stepped through the distances in order Km1, Mile1, Km2, Km3,
> Mile2, etc. so it just happened to put the colour the same for each of the
> same distance accross runs
>
> Now you have it do all the KM, than all the Mile
> so we could just specify a marker colour unique for each distance, and
> force it to use that marker colour
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/korymath/runkeeper-testing/issues/2#issuecomment-221365376>
>



-- 
____________________________
Kory Mathewson

**Comment by kylemath** [comment]
yes write a loop that just counts up in distance and hits all the km and mile markers as it does,
are you working on it?

**Comment by kylemath** [comment]
ok in the new branch I think I fixed the main problem and just run through the list of distances in order now
but the KM 3 and KM 4 are now labeled wrong, should be Km 2 and Km 3

![image](https://cloud.githubusercontent.com/assets/3662613/15517757/c3adc09a-21b6-11e6-89d4-aa84472b09b9.png)

**Comment by korymath** [comment]
Done and done. 

![alt](https://raw.githubusercontent.com/korymath/runkeeper-testing/master/new-example-compare.png)

**Comment by korymath** [comment]
Added RGB color for KM, and slightly diff for Miles. 

Also added some vlines, called in the build_marker, which can be easily commented out to disable. 

Also, obviously added some bigger markers, and lines, to actually see things from far away.

**Comment by kylemath** [comment]
I'm
confused what happened to my fork

On Tuesday, 24 May 2016, Kory <notifications@github.com> wrote:

> Closed #2 <https://github.com/korymath/runkeeper-testing/issues/2>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/korymath/runkeeper-testing/issues/2#event-670863016>
>


-- 
*Kyle E. Mathewson, Ph.D.*
Assistant Professor - Department of Psychology, Faculty of Science
Affiliate - Neuroscience and Mental Health Institute, Faculty of Medicine
and Dentistry
University of Alberta
P455 - Biological Sciences Building
11455 Saskatchewan Dr.
Edmonton, Alberta, Canada, T6G 2E9
Phone: 1-780-492-2662
Email: kyle.mathewson@ualberta.ca
Web: www.kylemathewson.com

**Comment by korymath** [comment]
The branches still exist. 

You can still find those branches in the main tree 
https://github.com/korymath/runkeeper-testing/tree/MarkerColourFix

But I was working on the master branch, so that is the default structure.
